"""Public record constants module."""

from enum import StrEnum


class Status(StrEnum):
    """Public record status."""

    SELECCIONAR = "- - SELECCIONAR - -"
    APELADO = "APELADO"
    BLOQUEO = "BLOQUEO"
    BLOQUEO_INSCRITO = "BLOQUEO INSCRITO"
    BUSQUEDA_REGISTRAL = "BUSQUEDA REGISTRAL"
    CRI = "C.R.I"
    CAMBIO_CARACT = "CAMBIO CARACT."
    CERTIFICADO_N = "CERTIF 'CADO N."
    CERTIFICADO_P = "CERTIF 'CADO P."
    COPIA_LITERAL = "COPIA LITERAL"
    DESCARGADO = "DESCARGADO"
    GRAVAMEN = "GRAVAMEN"
    INSCRITO = "INSCRITO"
    LIQUIDADO = "LIQUIDADO"
    OBSERVADO = "OBSERVADO"
    OBSERVADO_SUSPENDIDO = "OBSERVADO - SUSPENDIDO"
    PAGADO = "PAGADO"
    PRESENTADO = "PRESENTADO"
    PRESENTADO_EN_LINEA = "PRESENTADO EN LINEA"
    RECTIFICACION_OFICIO = "RECT. OFICIO"
    REINGRESADO = "REINGRESADO"
    REINGRESO_CON_PAGO = "REINGRESO CON PAGO"
    RESERVA_DE_NOMBRE = "RESERVA DE NOMBRE"
    SOLICITUD_TACHA = "SOLICITUD DE TACHA"
    TACHADO = "TACHADO"
    VIGENCIA = "VIGENCIA"
